DROP DATABASE IF EXISTS neu;
CREATE DATABASE neu;
USE neu;

-- C
CREATE TABLE class (
name VARCHAR(64) PRIMARY KEY, 
year VARCHAR(64) NOT NULL, 
semester VARCHAR(64) NOT NULL,
grade VARCHAR(64) DEFAULT NULL,
credits INT NOT NULL
);
